apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-server
  name: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - image: chrisduong/go-static-web-server
        imagePullPolicy: Always
        name: web-server
        resources: {}
