on:
  push:
    branches: [master]

name: Deploy

env:
  K8S_CLUSTER: attractive-painting-1643104019

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v2.0

      - name: Get Kubeconfig
        run: |
          aws eks update-kubeconfig --name ${K8S_CLUSTER}
          
      - name: Deploy into the K8s cluster
        run: |
          kubectl apply -f k8s
        # env:
        #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
